apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-prometheus-config
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'mlops-serving'
        metrics_path: /metrics
        static_configs:
          - targets:
              - mlops-serving:{{ .Values.serving.port }}
      - job_name: 'prometheus'
        static_configs:
          - targets:
              - localhost:9090
