apiVersion: v1
kind: Service
metadata:
  name: mlops-serving
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mlops-serving
  ports:
    - port: {{ .Values.serving.port }}
      targetPort: {{ .Values.serving.port }}
