apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MonDataa/MLOPS_end_to_end_cloud_native.git
    targetRevision: HEAD
    path: gitops/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
